### ISSUE TITLE
Publishing to prometheus pushgateway fails with Bad Request

### ISSUE THREAD

**Issue by vipsy** [cdsap/Talaiot#102]
Publishing to prometheus pushgateway fails with `Bad Request`
It is not printing HTTP response code either.  There should be more info in the logs to debug.

Output:
```
================
PushGatewayPublisher
publishBuildMetrics: true
publishTaskMetrics: false
================
http://prometheus-pushgateway:9091/metrics/job/task
== Build Time Summary ==
Bad Request
```

Here is my configuration
```
    talaiot {
        logger = com.cdsap.talaiot.logger.LogTracker.Mode.INFO
        publishers {
            pushGatewayPublisher {
                url = "http://prometheus-pushgateway:9091"
                publishBuildMetrics = true
                publishTaskMetrics = false
            }
        }

        filter {
            threshold {
                minExecutionTime = 1000
            }
        }
    }
```

A direct curl call works and pushes the metrics.
`"some_metric 3.14" | curl --data-binary @- http://prometheus-pushgateway:9091/metrics/job/some_job -v`

**Comment by cdsap** [comment]
hi @vipsy, thanks for the report. Checking now.

**Comment by cdsap** [comment]
hi, 
fixed in #103 and available snapshot here:
```
maven ( url = uri("http://oss.jfrog.org/artifactory/oss-snapshot-local") )
```

```
classpath("com.cdsap:talaiot:1.0.5-SNAPSHOT")
```

There were several problems:

* Formatting build metrics labels was incorrect. After the refactor of 1.x this problem was not catch.  That's why the error message
*  Both dimensions were submitting to the same job, now each one is reporting to specific job. 
*  No format for the error response. Now is property formatted.

Finally, I have added better logging in the INFO mode.

Please let me know if works for you, tomorrow I have plan to release the hotfix but I would like to include some E2E test for PushGateway, but I think there is no testcontainer available.

**Comment by cdsap** [comment]
hi, 
release 1.0.5 published. 
I've added a custom testcontainer for PushGateway for the e2e tests(#104 )

Problem reported in this issue fixed, please let me know if you have more problems.

**Comment by vipsy** [comment]
This has solved the original problem, Thank you.
Though there is a [follow-up issue](https://github.com/cdsap/Talaiot/issues/106) noticed

**Comment by cdsap** [comment]
solved
