### ISSUE TITLE
NoClassDefFoundError InternalBuildListener

### ISSUE THREAD

**Issue by hram** [cdsap/Talaiot#309]
Hi

Sync project ended with error
`Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/InternalBuildListener
	at io.github.cdsap.talaiot.Talaiot.setUpPlugin(Talaiot.kt:37)
	at io.github.cdsap.talaiot.plugin.TalaiotPlugin.apply(TalaiotPlugin.kt:15)
	at io.github.cdsap.talaiot.plugin.TalaiotPlugin.apply(TalaiotPlugin.kt:7)`

How can I identify matching versions gradle plugin and talaiot?

My current config:
- android gradle plugin version 3.6.4
- gradle version 5.6.4

**Comment by cdsap** [comment]
Hi, I'm afraid we are not supporting Gradle < 6 since Talaiot 1.4. 
The configuration you're showing is a bit behind(AGP 3.6.4/Gradle 5.6.4) but if you want still to use Talaiot on those versions you can use version 1.3.x: 
* https://plugins.gradle.org/plugin/com.cdsap.talaiot/1.3.5 
* https://github.com/cdsap/Talaiot/releases/tag/1.3.5
